### ISSUE TITLE
Upload large image

### ISSUE THREAD

**Issue by tatari2909** [Korchy/phpbb_imgur#1]
DONE

**Comment by Korchy** [comment]
You can change in **imgur.js** in **function uploadFile(vToken)** in string **var code = "[url=http://i.imgur.com/"+fileid+"."+fileext+"][img]http://i.imgur.com/"+fileid+"l."+fileext+"[/img][/url]";** to **var code = "[url=http://i.imgur.com/"+fileid+"."+fileext+"][img]http://i.imgur.com/"+fileid+"."+fileext+"[/img][/url]";** (remove "l" in image adress) to receive original image size from imgur.
