### ISSUE TITLE
ERROR: Bad website scheme. Did you forget 'http://' or 'https://'?

### ISSUE THREAD

**Issue by Owned67** [Korchy/phpbb_imgur#2]
API imgur return:
ERROR: Bad website scheme. Did you forget 'http://' or 'https://'?

http://i.imgur.com/zWQPcqx.png

**Comment by Korchy** [comment]
You can not register imgur application? Try to set https://domain.000webhostapp.com in Application website field in this form.

**Comment by Owned67** [comment]
imgur bug, it's ok :) thanks

**Comment by Pictor13** [comment]
Did they actually solved it? 2 years later I am having the same issue...

**Comment by Korchy** [comment]
I don't get this type of error. Can you check it?

**Comment by Pictor13** [comment]
It was an issue with imgur service. Tried later, changed browser, carefully retyped everything and it worked.
The issue is not with this repo, thanks for worrying :)
