### ISSUE TITLE
Add gallery

### ISSUE THREAD

**Issue by Owned67** [Korchy/phpbb_imgur#3]
Hello,

can you add to upload img to albums (multiple choice can be selected) if possible ?

I have: 
http://freeforfuns.imgur.com/

Ex:
http://zupimages.net/up/17/11/f5rp.jpg

Cheers,

Very nice script

**Comment by Korchy** [comment]
I write this to my to-do list, but realization (if it is possible) will be not soon.

**Comment by Owned67** [comment]
Oh ok :( but thanks for add to our todo, very nice!
