### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Owned67** [Korchy/phpbb_imgur#4]
Hello,

our script work fine but now i get this error and our script doesn't work...

POST https://api.imgur.com/3/image.json 403 (Permission Denied)
imgur.js:90 Uncaught TypeError: Cannot read property 'substr' of undefined
    at XMLHttpRequest.xhr.onload (imgur.js:90)

**Comment by Korchy** [comment]
Hello,
difficult to say without testing. Script can not authorize on imgur. Try to remove cookies imgur_token, imgur_refresh_token, imgur_expires from your browser and renew authorization via script.

To fix this globally, I need more information - what sequence of actions leads to that error?

**Comment by Owned67** [comment]
i have removed cache, cookie etc... regenrate secret ket => nothing...

I upload image => select case i have a account => Ok => error on console (F12).

edit: thanks for tip "remove imgur_token, imgur_refresh_token, imgur_expires ".

How to dit for get [img]http://i.imgur.com/UWumTQdl.jpg[/img] and not [url=http://i.imgur.com/UWumTQd.jpg][img]http://i.imgur.com/UWumTQdl.jpg[/img][/url] please?

Ok i have founded i think: 
var code = "[url=http://i.imgur.com/"+fileid+"."+fileext+"][img]http://i.imgur.com/"+fileid+"l."+fileext+"[/img][/url]";

replaced by:
var code = "[img]http://i.imgur.com/"+fileid+"l."+fileext+"[/img]";

**Comment by Korchy** [comment]
Edit imgur.js file in line number 91.
Yes, you are right.

Do removing cookies imgur_token, imgur_refresh_token, imgur_expires solved the authorization problem?

**Comment by Owned67** [comment]
Yes thanks
